### ISSUE TITLE
Hard to read header coloring of the API documentation

### ISSUE THREAD

**Issue by geoffmcl** [htacg/html-tidy.org.api#1]
At present the head of say http://api.html-tidy.org/tidy/tidylib_api_5.2.0/ is very difficult to read...

It is `white` text on a gray background, for `HTML Tidy 5.2.0`, and only a slightly darker gray for the next line `The HTACG Tidy HTML Project`... lack of contrast...

I know this is probably just a `css` include file issue, but can someone point me to where this is declared...

I have searched around a little, but can not quite put my finger on it... thanks...

**Comment by balthisar** [comment]
@geoffmcl, it looks like the color comes from **projectid** and **projectbrief** in _style.css_.

I pushed a change for the current site; I'll have to figure out where the CSS is generated by doxygen to ensure that we use a better color next time docs are generated.

Edit: only pushed the change for the current 5.2.0 docset.

**Comment by geoffmcl** [comment]
@balthisar that did the trick... thanks...

I have searched around on how to change this during doxygen html generation, but wow, that looks `difficult` ;=))

The best I have seen is to add to the doxygen config -

```
HTML_HEADER            =  header.html
HTML_FOOTER            = footer.html
HTML_STYLESHEET    = customstyle.css
```

and/or run doxygen with -

```
doxygen -w html header.html footer.html customstyle.css ...
```

But I then read somewhere that with the changing versions of doxygen that this can lead to rendering invalid html, so do not know...

But as you showed, it would not be difficult to do this small fix in post processing, during the manual copying and updating phase... so this would be just another small thing to remember...

OT: As you may have read [here](https://github.com/htacg/tidy-html5/issues/452), I am experimenting with having the latest version docs available for review, comment, discussion and adjusting **before** it is pushed to the official site... 

They are presently hosted here - http://tidy5docs-htacg.rhcloud.com/ - this gives me a convenient way to test, experiment **before** they are actually officially published... and you will note I have also manually applied this small css change there... thanks...

**Comment by geoffmcl** [comment]
@balthisar while generating my `test` 5.3.9 documentation, I got into fixing up some the doxygen comment syntax in the tidy **include** files, which I will push shortly. In most cases the changes were quite small... it effects all 6 files...

But also added two(2) changes to the `build_docs.sh` here... 
1. Why is tidyplatform.h excluded. Seems no reason to do this?
2. Added a `sed` quick fix for the `style.css` file...

The full suggested patch is -

``` patch
diff --git a/tidy-html5-doxygen/build_docs.sh b/tidy-html5-doxygen/build_docs.sh
index 8fccdd0..3f0b643 100755
--- a/tidy-html5-doxygen/build_docs.sh
+++ b/tidy-html5-doxygen/build_docs.sh
@@ -213,6 +213,9 @@ $TIDY_PATH -help-config > "$PATH_EXAMPLES/tidy.config.txt"
 # copy license file to examples for including
 cp "$PATH_LICENSE" "$PATH_EXAMPLES"

+## Why was this excluded?
+# echo "EXCLUDE=\"$PATH_INC/tidyplatform.h\""
+
 ## this lot 
 # - echoes and catches output of the doxygen config
 # - overwrites some vars but appending some to config at end
@@ -220,7 +223,6 @@ cp "$PATH_LICENSE" "$PATH_EXAMPLES"
 ( cat "$DOXY_CFG"; \
   echo "INPUT=\"$PATH_INC\" \"./\" \"./pages\""
   echo "INCLUDE_PATH=\"$PATH_SRC\""; \
-  echo "EXCLUDE=\"$PATH_INC/tidyplatform.h\""
   echo "OUTPUT_DIRECTORY=\"$OUTP_DIR\""
   echo "PROJECT_NUMBER=$TIDY_VERSION"; \
   echo "HTML_OUTPUT=\"$PATH_WEBSITE\""
@@ -228,6 +230,10 @@ cp "$PATH_LICENSE" "$PATH_EXAMPLES"
   echo "HTML_EXTRA_FILES= $PATH_EXAMPLES/tidy.help.txt $PATH_EXAMPLES/tidy.config.txt"; ) \
 | doxygen - > /dev/null

+# style fixup
+sed -i 's/color: white/color: black/g' "$OUTP_DIR/$PATH_WEBSITE/style.css"
+sed -i 's/color: #dddddd/color: black/g' "$OUTP_DIR/$PATH_WEBSITE/style.css"
+
 # cleanup
 rm "$PATH_EXAMPLES/tidy.help.txt"
 rm "$PATH_EXAMPLES/tidy.config.txt"
```

You could either apply this patch, or I could push it, if **all agreed**... please advise... thanks...

**Comment by balthisar** [comment]
Hmmm... I came here to close this after pushing the updates for 5.4, but hadn't noticed the proposed patch. I guess it's not important now, other than `tidyplatform.h` being excluded. I think it's excluded because it's _always_ been excluded, but I see no reason to hide it.

**Comment by geoffmcl** [comment]
Nor do I... seem it should be include...

**Comment by balthisar** [comment]
I've included `tidyplatform.h`, so will close this now.
