### ISSUE TITLE
Update of the 'next' API/QR online docs

### ISSUE THREAD

**Issue by geoffmcl** [htacg/html-tidy.org.api#6]
## Help Needed

It would really be appreciated if someone, anyone, would help with **updating** the `tidy/tidylib_api_next` folder...

Hopefully they could present a [Pull Request](https://github.com/htacg/html-tidy.org.api/pulls)...

The steps are basically - 

   1. fork the repo, clone your fork,
   2. cd `html-tidy.org.api/tidy-html5-doxygen`, and 
   3. run `./build_docs.sh`, some renaming, small fixes, and 
   4. copy the `output/<version>` folder, to replace `tidy/tidylib_api_next` contents 100%, 
   5. commit, push, and setup the PR...

Ask if you need further help, instructions, explanations, etc, etc...

Thanks, Geoff.

**Comment by balthisar** [comment]
Hope all is well! Pushed updates for 5.7.47, and are live now.
